#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg CASSANDRA_VERSION="3.11.9" \
    --build-arg CASSANDRA_ESUM="ada90233bcbb7bc572c24ff86a2ca2670df2955b1e451c53940faa640306c340e27933eeba013f8d4c4480e3842e5cdcd1563ac825ab4c6b036b5dbac356aa96" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
