#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg CASSANDRA_VERSION="3.11.5" \
    --build-arg CASSANDRA_ESUM="d559d351309ab4b702975abffae0663ffe6378cf7402c4bcb2f9b2b2f42ac7d017d7aa05f89ee523cab72d89c79d9fbc5ef692dfbb3f56d3993acd1f34cf1285" \
    --build-arg JAVA_SHA256SUM="7c97f078d34116e434467026d6740346af79558cc8628f27d36324f8ed67921b" \
    --build-arg JAVA_VERSION="11.0.6" \
    --build-arg ZULU_VERSION="11.37.17" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
